import type { TemplateDefinition } from "./types";

export const templates: TemplateDefinition[] = [
  // Paulinha Solo Templates
  {
    id: "paulinha-avatar-official-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · Avatar Circular Oficial",
    thumbnail: "/templates/thumbnails/paulinha-avatar-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.05, y: 0.05, width: 0.9, height: 0.6 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-avatar-quadrado-official-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · Feed Quadrado Oficial",
    thumbnail: "/templates/thumbnails/paulinha-avatar-quadrado-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.75 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-quadrado-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-avatar-apoio-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · EU APOIO 2020",
    thumbnail: "/templates/thumbnails/paulinha-avatar-apoio-v1.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.06, y: 0.02, width: 0.85, height: 0.72 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-apoio-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-story-derived-v1",
    identity: "paulinha",
    format: "story",
    label: "Paulinha · Story Oficial 9:16",
    thumbnail: "/templates/thumbnails/paulinha-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.09, width: 0.9, height: 0.7 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },

  // Emerson Stein Solo Templates
  {
    id: "emerson-avatar-official-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · Onda Azul Oficial",
    thumbnail: "/templates/thumbnails/emerson-avatar-official-v1.png",
    status: "human-supplied",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.7 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-avatar-circulo-official-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · Circular Oficial",
    thumbnail: "/templates/thumbnails/emerson-avatar-circulo-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.05, y: 0.05, width: 0.9, height: 0.65 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-circulo-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-avatar-apoio-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · EU APOIO 15100",
    thumbnail: "/templates/thumbnails/emerson-avatar-apoio-v1.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.75 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-apoio-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-story-derived-v1",
    identity: "emerson-stein",
    format: "story",
    label: "Emerson Stein · Story Oficial 9:16",
    thumbnail: "/templates/thumbnails/emerson-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.06, width: 0.9, height: 0.68 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },

  // Paulinha + Emerson Joint Templates
  {
    id: "duo-avatar-derived-v1",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Faixa Oficial Conjunta",
    thumbnail: "/templates/thumbnails/duo-avatar-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.76 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/avatar-derived-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-01",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Clássica Circular",
    thumbnail: "/templates/thumbnails/duo-avatar-01.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 1.0 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-01.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-02",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Faixa Superior & Inferior",
    thumbnail: "/templates/thumbnails/duo-avatar-02.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.13, y: 0.07, width: 0.73, height: 0.65 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-02.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-03",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Selo Circular EU APOIO",
    thumbnail: "/templates/thumbnails/duo-avatar-03.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 1.0 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-03.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-04",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Octogonal Dinâmica",
    thumbnail: "/templates/thumbnails/duo-avatar-04.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.14, y: 0.10, width: 0.72, height: 0.70 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-04.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-05",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · União Apertando as Mãos",
    thumbnail: "/templates/thumbnails/duo-avatar-05.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.12, y: 0.02, width: 0.76, height: 0.68 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-05.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-06",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Ondas Dinâmicas",
    thumbnail: "/templates/thumbnails/duo-avatar-06.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.16, y: 0.19, width: 0.68, height: 0.64 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-06.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-07",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Destaque Paulinha 2020",
    thumbnail: "/templates/thumbnails/duo-avatar-07.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.06, y: 0.02, width: 0.85, height: 0.72 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-07.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-08",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Destaque Emerson 15100",
    thumbnail: "/templates/thumbnails/duo-avatar-08.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.75 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-08.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-09",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Ondas com Selo Superior",
    thumbnail: "/templates/thumbnails/duo-avatar-09.png",
    status: "human-supplied-derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.10, y: 0.16, width: 0.79, height: 0.68 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/duo-avatar-09.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-story-derived-v1",
    identity: "paulinha-emerson",
    format: "story",
    label: "Paulinha + Emerson · Story Oficial 9:16",
    thumbnail: "/templates/thumbnails/duo-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.06, width: 0.9, height: 0.72 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },
];

export function getTemplates(identity: TemplateDefinition["identity"], format: TemplateDefinition["format"]) {
  return templates.filter((template) => template.identity === identity && template.format === format);
}
