import type { TemplateDefinition } from "./types";

export const templates: TemplateDefinition[] = [
  {
    id: "paulinha-avatar-official-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · Avatar Circular Oficial",
    thumbnail: "/templates/thumbnails/paulinha-avatar-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.05, y: 0.05, width: 0.9, height: 0.6 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-avatar-quadrado-official-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · Feed Quadrado Oficial",
    thumbnail: "/templates/thumbnails/paulinha-avatar-quadrado-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.75 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-quadrado-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-story-derived-v1",
    identity: "paulinha",
    format: "story",
    label: "Paulinha · Story Oficial 9:16",
    thumbnail: "/templates/thumbnails/paulinha-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.09, width: 0.9, height: 0.7 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-avatar-official-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · Onda Azul Oficial",
    thumbnail: "/templates/thumbnails/emerson-avatar-official-v1.png",
    status: "human-supplied",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.7 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-avatar-circulo-official-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · Circular Oficial",
    thumbnail: "/templates/thumbnails/emerson-avatar-circulo-official-v1.png",
    status: "official-source",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.05, y: 0.05, width: 0.9, height: 0.65 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-circulo-official-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-story-derived-v1",
    identity: "emerson-stein",
    format: "story",
    label: "Emerson Stein · Story Oficial 9:16",
    thumbnail: "/templates/thumbnails/emerson-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.06, width: 0.9, height: 0.68 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-avatar-derived-v1",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Avatar Conjunto",
    thumbnail: "/templates/thumbnails/duo-avatar-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1080,
    photoArea: { x: 0.0, y: 0.0, width: 1.0, height: 0.76 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/avatar-derived-v1.png" }],
    export: { mime: "image/png" },
  },
  {
    id: "duo-story-derived-v1",
    identity: "paulinha-emerson",
    format: "story",
    label: "Paulinha + Emerson · Story Conjunto 9:16",
    thumbnail: "/templates/thumbnails/duo-story-derived-v1.png",
    status: "derived",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.05, y: 0.06, width: 0.9, height: 0.72 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/story-derived-v1.png" }],
    export: { mime: "image/png" },
  },
];

export function getTemplates(identity: TemplateDefinition["identity"], format: TemplateDefinition["format"]) {
  return templates.filter((template) => template.identity === identity && template.format === format);
}
