import type { TemplateDefinition } from "./types";

export const templates: TemplateDefinition[] = [
  {
    id: "paulinha-avatar-placeholder-v1",
    identity: "paulinha",
    format: "avatar",
    label: "Paulinha · Avatar · Placeholder",
    width: 1080,
    height: 1080,
    photoArea: { x: 0, y: 0, width: 1, height: 1 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha/avatar-placeholder.svg" }],
    export: { mime: "image/png" },
  },
  {
    id: "paulinha-story-placeholder-v1",
    identity: "paulinha",
    format: "story",
    label: "Paulinha · Story · Placeholder",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.08, y: 0.16, width: 0.84, height: 0.62 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha/story-placeholder.svg" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-avatar-placeholder-v1",
    identity: "emerson-stein",
    format: "avatar",
    label: "Emerson Stein · Avatar · Placeholder",
    width: 1080,
    height: 1080,
    photoArea: { x: 0, y: 0, width: 1, height: 1 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/avatar-placeholder.svg" }],
    export: { mime: "image/png" },
  },
  {
    id: "emerson-story-placeholder-v1",
    identity: "emerson-stein",
    format: "story",
    label: "Emerson Stein · Story · Placeholder",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.08, y: 0.16, width: 0.84, height: 0.62 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/emerson-stein/story-placeholder.svg" }],
    export: { mime: "image/png" },
  },
  {
    id: "dupla-avatar-placeholder-v1",
    identity: "paulinha-emerson",
    format: "avatar",
    label: "Paulinha + Emerson · Avatar · Placeholder",
    width: 1080,
    height: 1080,
    photoArea: { x: 0, y: 0, width: 1, height: 1 },
    cropShape: "round",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/avatar-placeholder.svg" }],
    export: { mime: "image/png" },
  },
  {
    id: "dupla-story-placeholder-v1",
    identity: "paulinha-emerson",
    format: "story",
    label: "Paulinha + Emerson · Story · Placeholder",
    width: 1080,
    height: 1920,
    photoArea: { x: 0.08, y: 0.16, width: 0.84, height: 0.62 },
    cropShape: "rect",
    layers: [{ type: "overlay", src: "/templates/paulinha-emerson/story-placeholder.svg" }],
    export: { mime: "image/png" },
  },
];

export function getTemplates(identity: TemplateDefinition["identity"], format: TemplateDefinition["format"]) {
  return templates.filter((template) => template.identity === identity && template.format === format);
}
